<?php

namespace QualityCode\ApiFeaturesBundle\Tests\App\Repository;

use Doctrine\ORM\EntityRepository;
use QualityCode\ApiFeaturesBundle\Repository\PaginationAndSortingFeaturesTrait;

/**
 * AdresseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FakeRepository extends EntityRepository
{
    use PaginationAndSortingFeaturesTrait;
}
